name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_DOCKER_HELLOWORLD }}
      - name: Build the hello-docker Docker image
        run: |
         docker build . --tag ghcr.io/roobann/docker-helloworld:latest
         docker run ghcr.io/roobann/docker-helloworld:latest
         docker push ghcr.io/roobann/docker-helloworld:latest
      - name: Image pushed
        run: echo "pushed"
        
